{%if uvm is defined%}
VCS_UVM_HOME=${VCS_HOME}/etc/{{uvm}}
UVM_TESTNAME?={{test_name}}
{%endif%}

all: {{ name }}

{%if c_dpi_files -%}
CC = gcc
{%if c_dpi_dir -%}
DPI_INCDIR ={%for dir in c_dpi_dir%} {{dir}}{%endfor%}
{%-endif%}

DPI_C_SRC ={%for src in c_dpi_files%} {{src.name}}{%endfor%}

DPI_OBJS  = $(DPI_C_SRC:.c=.o)

%.o: %.c
	${CC} -fPIC -O2 -I${VCS_HOME}/include {%if c_dpi_dir%}-I${DPI_INCDIR}{%endif%} -c $< -o $@

libdpi.so : ${DPI_OBJS}
	${CC} -shared -fPIC -o $@ $^
{%-endif%}

{{ name }}: work
	vlogan -sverilog -q -full64 ${XILINX_VIVADO}/data/verilog/src/glbl.v
	$(EDALIZE_LAUNCHER) vcs -full64 -CFLAGS "-I/usr/include/x86_64-linux-gnu" work.glbl {%if uvm is defined%} ${VCS_UVM_HOME}/dpi/uvm_dpi.cc {%endif%} work.{{ toplevel }} -o $@ {% for option in vcs_options %}{{ option }} {% endfor %}  {%-if uvm is defined%} -CFLAGS -DVCS{%endif%} -parameters parameters.snps 2>&1 | tee -a vcs_build.log

{%if c_dpi_files %}
run: {{ name }} libdpi.so
{%else%}
run: {{ name }}
{%endif%}
	{{ beforearg }} ./{{ name }} -l vcs_run.log {% for plusarg in plusargs %} {{ plusarg }} {% endfor %}{% for option in run_options %} {{ option }}{% endfor %} {%if c_dpi_files %}-sv_lib libdpi{%endif%} {%if uvm is defined%} +UVM_TESTNAME=${UVM_TESTNAME} {%endif%}


work: analyze.bash
	mkdir -p work
	cp ${VCS_HOME}/bin/synopsys_sim.setup .
	echo "WORK  > default" >> synopsys_sim.setup
	echo "default : ./work" >> synopsys_sim.setup
	{%if uvm is defined%}
	vlogan -ntb_opts {{uvm}}
	{%endif%}
	bash -x analyze.bash 2>&1 | tee vcs_build.log

clean:
	$(RM) {{ name }}
