all: {{ name }}

{{ name }}: work
	$(EDALIZE_LAUNCHER) vcs -full64 -CFLAGS "-I/usr/include/x86_64-linux-gnu" work.{{ toplevel }} -o $@ {% for option in vcs_options %}{{ option }} {% endfor %} -parameters parameters.snps


run: {{ name }}
	{{ beforearg }} ./{{ name }} -l vcs.log {% for plusarg in plusargs %} {{ plusarg }} {% endfor %}{% for option in run_options %} {{ option }}{% endfor %}


work: analyze.bash
	mkdir -p work
	cp ${VCS_HOME}/bin/synopsys_sim.setup .
	echo "WORK  > default" >> synopsys_sim.setup
	echo "default : ./work" >> synopsys_sim.setup
	bash -x analyze.bash

clean:
	$(RM) {{ name }}
